#include "Data.h"

std::unordered_map<sc2::ABILITY_ID, std::unordered_set<sc2::UNIT_TYPEID>> scdata::UnitRequirements {
    {sc2::ABILITY_ID::BUILD_NEXUS, {}},
    {sc2::ABILITY_ID::BUILD_PYLON, {}},
    {sc2::ABILITY_ID::BUILD_ASSIMILATOR, {sc2::UNIT_TYPEID::PROTOSS_NEXUS}},
    {sc2::ABILITY_ID::BUILD_GATEWAY, {sc2::UNIT_TYPEID::PROTOSS_PYLON}},
    {sc2::ABILITY_ID::BUILD_FORGE, {sc2::UNIT_TYPEID::PROTOSS_PYLON}},
    {sc2::ABILITY_ID::BUILD_CYBERNETICSCORE, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_GATEWAY}},
    {sc2::ABILITY_ID::BUILD_ROBOTICSFACILITY, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE}},
    {sc2::ABILITY_ID::BUILD_STARGATE, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE}},
    {sc2::ABILITY_ID::BUILD_TEMPLARARCHIVE, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE}},
    {sc2::ABILITY_ID::BUILD_DARKSHRINE, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE}},
    {sc2::ABILITY_ID::BUILD_TWILIGHTCOUNCIL, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE}},
    {sc2::ABILITY_ID::BUILD_FLEETBEACON, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_STARGATE}},
    {sc2::ABILITY_ID::BUILD_ROBOTICSBAY, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY}},
    {sc2::ABILITY_ID::BUILD_PHOTONCANNON, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_FORGE}},
    {sc2::ABILITY_ID::TRAIN_PROBE, {sc2::UNIT_TYPEID::PROTOSS_NEXUS}},
    {sc2::ABILITY_ID::TRAIN_ZEALOT, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_GATEWAY}},
    {sc2::ABILITY_ID::TRAIN_STALKER, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_GATEWAY, sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE}},
    {sc2::ABILITY_ID::TRAIN_SENTRY, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_GATEWAY, sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE}},
    {sc2::ABILITY_ID::TRAIN_ADEPT, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_GATEWAY, sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE}},
    {sc2::ABILITY_ID::TRAIN_HIGHTEMPLAR, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_GATEWAY, sc2::UNIT_TYPEID::PROTOSS_TEMPLARARCHIVE}},
    {sc2::ABILITY_ID::TRAIN_DARKTEMPLAR, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_GATEWAY, sc2::UNIT_TYPEID::PROTOSS_DARKSHRINE}},
    {sc2::ABILITY_ID::TRAIN_CARRIER, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_STARGATE, sc2::UNIT_TYPEID::PROTOSS_FLEETBEACON}},
    {sc2::ABILITY_ID::TRAIN_VOIDRAY, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_STARGATE}},
    {sc2::ABILITY_ID::TRAIN_OBSERVER, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY}},
    {sc2::ABILITY_ID::TRAIN_WARPPRISM, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY}},
    {sc2::ABILITY_ID::TRAIN_IMMORTAL, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY}},
    {sc2::ABILITY_ID::TRAIN_COLOSSUS, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSBAY}},
    {sc2::ABILITY_ID::TRAIN_DISRUPTOR, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSBAY}},
    {sc2::ABILITY_ID::TRAIN_PHOENIX, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_STARGATE}},
    {sc2::ABILITY_ID::TRAIN_ORACLE, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_STARGATE}},
    {sc2::ABILITY_ID::TRAIN_TEMPEST, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_STARGATE, sc2::UNIT_TYPEID::PROTOSS_FLEETBEACON}},
    {sc2::ABILITY_ID::TRAIN_MOTHERSHIP, {sc2::UNIT_TYPEID::PROTOSS_PYLON, sc2::UNIT_TYPEID::PROTOSS_FLEETBEACON}}
};

std::unordered_set<sc2::UNIT_TYPEID> scdata::PoweredStructures {
    sc2::UNIT_TYPEID::PROTOSS_GATEWAY,
    sc2::UNIT_TYPEID::PROTOSS_FORGE,
    sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE,
    sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY,
    sc2::UNIT_TYPEID::PROTOSS_STARGATE,
    sc2::UNIT_TYPEID::PROTOSS_TEMPLARARCHIVE,
    sc2::UNIT_TYPEID::PROTOSS_DARKSHRINE,
    sc2::UNIT_TYPEID::PROTOSS_TWILIGHTCOUNCIL,
    sc2::UNIT_TYPEID::PROTOSS_FLEETBEACON,
    sc2::UNIT_TYPEID::PROTOSS_ROBOTICSBAY,
    sc2::UNIT_TYPEID::PROTOSS_PHOTONCANNON
};

std::unordered_set<sc2::ABILITY_ID> scdata::MiningAbilities {
    sc2::ABILITY_ID::HARVEST_GATHER,
    sc2::ABILITY_ID::HARVEST_RETURN,
    sc2::ABILITY_ID::HARVEST_GATHER_PROBE,
    sc2::ABILITY_ID::HARVEST_RETURN_PROBE
};

std::unordered_map<sc2::ABILITY_ID, scdata::AbilityCost> scdata::AbilityCosts {
    {sc2::ABILITY_ID::BUILD_NEXUS, {400, 0}},
    {sc2::ABILITY_ID::BUILD_PYLON, {100, 0}},
    {sc2::ABILITY_ID::BUILD_ASSIMILATOR, {75, 0}},
    {sc2::ABILITY_ID::BUILD_GATEWAY, {150, 0}},
    {sc2::ABILITY_ID::BUILD_FORGE, {150, 0}},
    {sc2::ABILITY_ID::BUILD_CYBERNETICSCORE, {150, 0}},
    {sc2::ABILITY_ID::BUILD_ROBOTICSFACILITY, {200, 100}},
    {sc2::ABILITY_ID::BUILD_STARGATE, {150, 150}},
    {sc2::ABILITY_ID::BUILD_TEMPLARARCHIVE, {150, 200}},
    {sc2::ABILITY_ID::BUILD_DARKSHRINE, {150, 150}},
    {sc2::ABILITY_ID::BUILD_TWILIGHTCOUNCIL, {150, 100}},
    {sc2::ABILITY_ID::BUILD_FLEETBEACON, {300, 200}},
    {sc2::ABILITY_ID::BUILD_ROBOTICSBAY, {200, 200}},
    {sc2::ABILITY_ID::BUILD_PHOTONCANNON, {150, 0}},
    {sc2::ABILITY_ID::TRAIN_PROBE, {50, 0}},
    {sc2::ABILITY_ID::TRAIN_ZEALOT, {100, 0}},
    {sc2::ABILITY_ID::TRAIN_STALKER, {125, 50}},
    {sc2::ABILITY_ID::TRAIN_SENTRY, {50, 100}},
    {sc2::ABILITY_ID::TRAIN_ADEPT, {100, 25}},
    {sc2::ABILITY_ID::TRAIN_HIGHTEMPLAR, {50, 150}},
    {sc2::ABILITY_ID::TRAIN_DARKTEMPLAR, {125, 125}},
    {sc2::ABILITY_ID::TRAIN_CARRIER, {350, 250}},
    {sc2::ABILITY_ID::TRAIN_VOIDRAY, {250, 150}},
    {sc2::ABILITY_ID::TRAIN_OBSERVER, {25, 75}},
    {sc2::ABILITY_ID::TRAIN_WARPPRISM, {200, 0}},
    {sc2::ABILITY_ID::TRAIN_IMMORTAL, {275, 100}},
    {sc2::ABILITY_ID::TRAIN_COLOSSUS, {300, 200}},
    {sc2::ABILITY_ID::TRAIN_DISRUPTOR, {150, 150}},
    {sc2::ABILITY_ID::TRAIN_PHOENIX, {150, 100}},
    {sc2::ABILITY_ID::TRAIN_ORACLE, {150, 150}},
    {sc2::ABILITY_ID::TRAIN_TEMPEST, {300, 200}},
    {sc2::ABILITY_ID::TRAIN_MOTHERSHIP, {300, 300}},
};

std::unordered_map<sc2::ABILITY_ID, sc2::UNIT_TYPEID> scdata::TrainBuilding {
    {sc2::ABILITY_ID::TRAIN_PROBE, sc2::UNIT_TYPEID::PROTOSS_NEXUS},
    {sc2::ABILITY_ID::TRAIN_ZEALOT, sc2::UNIT_TYPEID::PROTOSS_GATEWAY},
    {sc2::ABILITY_ID::TRAIN_STALKER, sc2::UNIT_TYPEID::PROTOSS_GATEWAY},
    {sc2::ABILITY_ID::TRAIN_SENTRY, sc2::UNIT_TYPEID::PROTOSS_GATEWAY},
    {sc2::ABILITY_ID::TRAIN_ADEPT, sc2::UNIT_TYPEID::PROTOSS_GATEWAY},
    {sc2::ABILITY_ID::TRAIN_HIGHTEMPLAR, sc2::UNIT_TYPEID::PROTOSS_GATEWAY},
    {sc2::ABILITY_ID::TRAIN_DARKTEMPLAR, sc2::UNIT_TYPEID::PROTOSS_GATEWAY},
    {sc2::ABILITY_ID::TRAIN_CARRIER, sc2::UNIT_TYPEID::PROTOSS_STARGATE},
    {sc2::ABILITY_ID::TRAIN_VOIDRAY, sc2::UNIT_TYPEID::PROTOSS_STARGATE},
    {sc2::ABILITY_ID::TRAIN_OBSERVER, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY},
    {sc2::ABILITY_ID::TRAIN_WARPPRISM, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY},
    {sc2::ABILITY_ID::TRAIN_IMMORTAL, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY},
    {sc2::ABILITY_ID::TRAIN_COLOSSUS, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY},
    {sc2::ABILITY_ID::TRAIN_DISRUPTOR, sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY},
    {sc2::ABILITY_ID::TRAIN_PHOENIX, sc2::UNIT_TYPEID::PROTOSS_STARGATE},
    {sc2::ABILITY_ID::TRAIN_ORACLE, sc2::UNIT_TYPEID::PROTOSS_STARGATE},
    {sc2::ABILITY_ID::TRAIN_TEMPEST, sc2::UNIT_TYPEID::PROTOSS_STARGATE},
    {sc2::ABILITY_ID::TRAIN_MOTHERSHIP, sc2::UNIT_TYPEID::PROTOSS_NEXUS}
};

std::unordered_set<sc2::ABILITY_ID> scdata::UnitTrainTypes {
    sc2::ABILITY_ID::TRAIN_PROBE,
    sc2::ABILITY_ID::TRAIN_ZEALOT,
    sc2::ABILITY_ID::TRAIN_STALKER,
    sc2::ABILITY_ID::TRAIN_SENTRY,
    sc2::ABILITY_ID::TRAIN_ADEPT,
    sc2::ABILITY_ID::TRAIN_HIGHTEMPLAR,
    sc2::ABILITY_ID::TRAIN_DARKTEMPLAR,
    sc2::ABILITY_ID::TRAIN_CARRIER,
    sc2::ABILITY_ID::TRAIN_VOIDRAY,
    sc2::ABILITY_ID::TRAIN_OBSERVER,
    sc2::ABILITY_ID::TRAIN_WARPPRISM,
    sc2::ABILITY_ID::TRAIN_IMMORTAL,
    sc2::ABILITY_ID::TRAIN_COLOSSUS,
    sc2::ABILITY_ID::TRAIN_DISRUPTOR,
    sc2::ABILITY_ID::TRAIN_PHOENIX,
    sc2::ABILITY_ID::TRAIN_ORACLE,
    sc2::ABILITY_ID::TRAIN_TEMPEST,
    sc2::ABILITY_ID::TRAIN_MOTHERSHIP
};

std::unordered_map<sc2::ABILITY_ID, sc2::ABILITY_ID> scdata::UnitTrainAbilityWarpTypes {
    {sc2::ABILITY_ID::TRAIN_ZEALOT, sc2::ABILITY_ID::TRAINWARP_ZEALOT},
    {sc2::ABILITY_ID::TRAIN_STALKER, sc2::ABILITY_ID::TRAINWARP_STALKER},
    {sc2::ABILITY_ID::TRAIN_SENTRY, sc2::ABILITY_ID::TRAINWARP_SENTRY},
    {sc2::ABILITY_ID::TRAIN_ADEPT, sc2::ABILITY_ID::TRAINWARP_ADEPT},
    {sc2::ABILITY_ID::TRAIN_HIGHTEMPLAR, sc2::ABILITY_ID::TRAINWARP_HIGHTEMPLAR},
    {sc2::ABILITY_ID::TRAIN_DARKTEMPLAR, sc2::ABILITY_ID::TRAINWARP_DARKTEMPLAR}
};